### ISSUE TITLE
Problems with Enzyme

### ISSUE THREAD

**Issue by simsurace** [JuliaGaussianProcesses/ParameterHandling.jl#59]
I'm not sure whether this is a bug in ParameterHandling or Enzyme:
```julia
using Enzyme
using ParameterHandling

f(θ) = θ.a + θ.b

θ1 = (a = fixed(1.), b = positive(1.));
x1, unpack1 = ParameterHandling.value_flatten(θ1);
bx1 = zeros(length(x1));
autodiff(Reverse, (f, x, unpack) -> f(unpack(x)), f, Duplicated(x1, bx1), unpack1);

θ2 = (a = fixed(1.), b = positive(1.), c = fixed(1.));
x2, unpack2 = ParameterHandling.value_flatten(θ2);
bx2 = zeros(length(x2));
autodiff(Reverse, (f, x, unpack) -> f(unpack(x)), f, Duplicated(x2, bx2), unpack2);

f(unpack1(x1)) ≈ f(unpack2(x2)) # true
bx1 ≈ bx2 # false
```
EDIT: important note: it occurs on Julia 1.9 but not on 1.8.

**Comment by willtebbutt** [comment]
Thanks for opening this. I don't see how it would be an issue with ParameterHandling, as I don't believe ParameterHandling does anything that changes how Enzyme operates (i.e. we don't define any rules that it uses or anything). Probably best to open an issue in Enzyme.

**Comment by simsurace** [comment]
Yeah, you are probably right. I will open an issue there.

**Comment by simsurace** [comment]
https://github.com/EnzymeAD/Enzyme.jl/issues/691
