### ISSUE TITLE
Why constructor instead of `identity`

### ISSUE THREAD

**Issue by simsurace** [JuliaGaussianProcesses/ParameterHandling.jl#60]
I was wondering why a constructor is used for the unflatten function in 

https://github.com/JuliaGaussianProcesses/ParameterHandling.jl/blob/e5e03d1b7bdfffc5d9dbc119fa2f967599071d99/src/flatten.jl#L34

instead of simply the `identity`.

Context: I was chasing an Enzyme error. The following doesn't work:
```julia
using Enzyme, ParameterHandling
testfun(θ) = sum(θ[1])
θ = (rand(10),)
x, unpack = value_flatten(θ)
dx = zero(x)
autodiff(Reverse, testfun ∘ unpack, Duplicated(x, dx)) # ERROR: Duplicated Returns not yet handled
```
But when overloading `flatten` for vectors as follows, it works ok.

```julia
ParameterHandling.flatten(::Type{T}, x::Vector{R}) where {T<:Real,R<:Real} = (Vector{T}(x), identity)
```
There's probably a bug somewhere in Enzyme which makes it so it can't differentiate this,, but as always I find it pretty hard to reduce to a MWE.

**Comment by willtebbutt** [comment]
I suspect that we implemented it this way to enforce that a vector with element type `R` is produced when un-flattening. e.g. if `T == Float64` and `R == Float32`, I believe we wanted to ensure that
```julia
v, unflatten = flatten(Float32, randn(3))
x_ = unflatten(v)
```
produces `x_` with element-type `Float64`, rather than `Float32`.

**Comment by simsurace** [comment]
Yeah makes sense. I guess one could add a specialization for `T==R` though with the identity.

**Comment by willtebbutt** [comment]
That definitely makes sense as a work-around to have in your code for now, but I'd rather not add it to this package. I'd be happy to help constructing a MWE in order to open an issue on Enzyme. Do you have a starting point for the example?

**Comment by simsurace** [comment]
Sure, I wasn't suggesting adding it to the package. The MWE is basically in the second code block in the OP. I already tried with just a vector (i.e. not wrapped in a `Tuple`), but then the error does not occur. So I suspect it has to do with the constructor appearing in the `ComposedFunction`, but it's really just a speculation on my part right now.

**Comment by simsurace** [comment]
Never mind the last comment, the following also does not work:
```julia
using Enzyme, ParameterHandling
testfun(θ) = sum(θ[1])
θ = (rand(10),)
x, unpack = flatten(θ)
dx = zero(x)
autodiff(Reverse, testfun ∘ unpack, Duplicated(x, dx))
```

**Comment by simsurace** [comment]
Yes I often see that but I was told that it's not really a problem. The error I see is
```
ERROR: Duplicated Returns not yet handled
```

**Comment by willtebbutt** [comment]
Oh, interesting, I didn't see that with
```julia
autodiff(Reverse, testfun ∘ Vector{Float64}, Duplicated(x ,dx))
```
Hmmmm

**Comment by simsurace** [comment]
https://github.com/EnzymeAD/Enzyme.jl/issues/741

**Comment by simsurace** [comment]
After the response and further thought it seems that this is really not an Enzyme bug. The problem is that in the first example a closure over `constructor` is created, which implicitly creates a `struct` with field type `DataType`. Indeed:
```julia
julia> @code_warntype foo(t)
MethodInstance for foo(::Tuple{Vector{Float64}})
  from foo(x::Tuple{T}) where T<:(AbstractVector) in Main at /home/simone_a/Documents/projects/n/ai-timeseries-julia/tsv.jl:130
Static Parameters
  T = Vector{Float64}
Arguments
  #self#::Core.Const(foo)
  x::Tuple{Vector{Float64}}
Locals
  bar::var"#bar#15"{DataType}
  constructor::Type{Vector{Float64}}
  TT::Type{Vector{Float64}}
Body::Tuple{Vector{Float64}, var"#bar#15"{DataType}} # <--- HERE
1 ─ %1  = Main.only(x)::Vector{Float64}
│   %2  = Main.typeof(%1)::Core.Const(Vector{Float64})
│   %3  = Core.apply_type(Main.Type, $(Expr(:static_parameter, 1)))::Core.Const(Type{Vector{Float64}})
│         (constructor = Core.typeassert(%2, %3))
│   %5  = constructor::Core.Const(Vector{Float64})
│         (TT = %5)
│   %7  = Main.:(var"#bar#15")::Core.Const(var"#bar#15")
│   %8  = Core.typeof(TT::Core.Const(Vector{Float64}))::Core.Const(DataType)
│   %9  = Core.apply_type(%7, %8)::Core.Const(var"#bar#15"{DataType})
│         (bar = %new(%9, TT::Core.Const(Vector{Float64})))
│         (bar = bar::Core.Const(var"#bar#15"{DataType}(Vector{Float64})))
│   %12 = Main.only(x)::Vector{Float64}
│   %13 = Core.tuple(%12, bar::Core.Const(var"#bar#15"{DataType}(Vector{Float64})))::Core.PartialStruct(Tuple{Vector{Float64}, var"#bar#15"{DataType}}, Any[Vector{Float64}, Core.Const(var"#bar#15"{DataType}(Vector{Float64}))])
└──       return %13
```
and therefore
```julia
julia> @code_warntype u(x)
MethodInstance for (::var"#bar#15"{DataType})(::Vector{Float64})
  from (::var"#bar#15")(v) in Main at /home/simone_a/Documents/projects/n/ai-timeseries-julia/tsv.jl:133
Arguments
  #self#::var"#bar#15"{DataType}
  v::Vector{Float64}
Body::Tuple{Any}
1 ─ %1 = Core.getfield(#self#, :TT)::DataType
│   %2 = (%1)(v)::Any
│   %3 = Core.tuple(%2)::Tuple{Any}
└──      return %3
```
In the full example the problem is the same.

**Comment by willtebbutt** [comment]
Ahh I see. So perhaps we should replace the `Vector{R}` with something else, like `x -> convert(Vector{R}, x)`?

**Comment by simsurace** [comment]
I found a fix. It is sufficient to make the `unflatten_to_Vector` more explicit using broadcast:
```julia
function flatten(::Type{T}, x::Vector{R}) where {T<:Real,R<:Real}
    function unflatten_to_Vector(v::Vector{T})
        return R.(v)
    end
    return Vector{T}(x), unflatten_to_Vector
end
```
Would you mind this change?

**Comment by simsurace** [comment]
> Ahh I see. So perhaps we should replace the Vector{R} with something else, like x -> convert(Vector{R}, x)?

That might work as well. Let me try.
